# Generated by Django 2.0.2 on 2018-02-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='username', max_length=50, unique=True, verbose_name='email'),
        ),
    ]
